version: '3.4'
services:

  base-ubuntu:
    image: base-ubuntu:v1
    build:
      context: ./base-ubuntu
      dockerfile: Dockerfile
      network: host
      target: base-ubuntu
    privileged: false

  ct-ng:
    image: crosstool-ng:v1
    build:
      context: ./crosstool-ng
      dockerfile: Dockerfile
      network: host
      target: ct-ng
    privileged: false

  aarch64-toolchain:
    image: aarch64-toolchain:v1
    container_name: aarch64-toolchain
    build:
      context: ./aarch64-toolchain
      dockerfile: Dockerfile
      network: host
      target: aarch64-toolchain
    privileged: false
    depends_on:
      - ct-ng

  aarch64-installed:
    image: aarch64-installed:v1
    container_name: aarch64-installed
    build:
      context: ./aarch64-installed
      dockerfile: Dockerfile
      network: host
      target: aarch64-installed
    privileged: false
    depends_on:
      - base-ubuntu
      - aarch64-toolchain

  aarch32-toolchain:
    image: aarch32-toolchain:v1
    container_name: aarch32-toolchain
    build:
      context: ./aarch32-toolchain
      dockerfile: Dockerfile
      network: host
      target: aarch32-toolchain
    privileged: false
    depends_on:
      - ct-ng

  aarch32-installed:
    image: aarch32-installed:v1
    container_name: aarch32-installed
    build:
      context: ./aarch32-installed
      dockerfile: Dockerfile
      network: host
      target: aarch32-installed
    privileged: false
    depends_on:
      - base-ubuntu
      - aarch32-toolchain