version: "3"

services:
  distcc-server:
    build:
      context: .
    image: aarch64-cross-toolchain-distcc
    container_name: aarch64-cross-toolchain-distcc-server
    networks: 
      - distcc_network
    entrypoint: 
      "bash -c '\
          distccd --daemon \
                  --allow 0.0.0.0/0 \
                  --nice 0 \
                  --log-file distcc.log \
          && tail -f distcc.log'"
  client:
    image: aarch64-develop
    container_name: aarch64-develop-distcc-client
    stdin_open: true
    tty: true
    environment:
      DISTCC_HOSTS: 'distcc-server,cpp,lzo'
    networks:
      - distcc_network
    entrypoint: bash

networks: 
  distcc_network:
